# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 天融信开源软件镜像站
# title: 北京外国语大学开源软件镜像站
school: 天融信
# school: 北京外国语大学
brand: Tsinghua Open Source Mirror
operator: 天融信大数据技术中心
# operator: 北外信息技术中心
logo: true
meow_404: true
issue_tag: tsc
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "http://mirrors.topsec.com.cn"
hostname: "mirrors.topsec.com.cn"
urlv4: "http://mirrors4.topsec.com.cn"
urlv6: "http://mirrors6.topsec.com.cn"
aosp: "aosp.topsec.com.cn"
arch_archive: "arch-archive.topsec.com.cn"
aur: "aur.topsec.com.cn"
pypi: "pypi.topsec.com.cn"
homelink: "https://www.topsec.com.cn"
hide_navbar: false
hide_download: false
hide_server_status: false

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

# vim: ts=2 sts=2 sw=2 expandtab
